### ISSUE TITLE
Hogan.js is unmaintained

### ISSUE THREAD

**Issue by SydneyUni-Jim** [rtfpessoa/diff2html#435]
https://github.com/twitter/hogan.js/issues/272 (2 May 2021)

> It's been ~8 years since I seriously worked on this project […] After this work is done, I'll add a note to the README that makes it clear the project is not adding new features, and is in maintenance mode. Serious bugs, such as security issues, will be addressed. New features and performance work can be done in a fork.

The last time a pull request was closed was 8 Jun 2019. The dependencies in hogan.js are becoming deprecated (https://github.com/twitter/hogan.js/pull/270) and security vulnerabilities are being exposed (https://github.com/twitter/hogan.js/pull/276).

**Comment by rtfpessoa** [comment]
👋 I understand that it is not being maintained anymore but it has been very stable and fits very well the use case.

Do you have any alternatives we can use?

Also AFAIK we have no active vulns https://github.com/rtfpessoa/diff2html/security/dependabot

**Comment by jgonggrijp** [comment]
@rtfpessoa I'm currently developing [Wontache](https://jgonggrijp.gitlab.io/wontache/), which can be thought of as a successor of hogan.js (although the code bases are not actually related). I haven't reached the 1.0.0 release yet, but it's fully tested, passes all the official Mustache specs (including the newest) and is even more accurate at whitespace handling than hogan.js. In my own testing, it also seems to be at least as fast as hogan.js, but you might want to try that for yourself on a feature branch.

The API is slightly different, the compiler returns a function that you can then call with the data:

```js
import mustache from 'wontache';

const templateText = 'Interpolate {{variable}} here.';
const compiledTemplate = mustache(templateText);
const renderedOutput = compiledTemplate({variable: 'foo'});
// 'Interpolate foo here.'
```

While I'm not proud enough yet to draw a lot of attention to Wontache, I would definitely welcome diff2html as a first serious outside user.

**Comment by rtfpessoa** [comment]
👋 @jgonggrijp did a [quick test](https://github.com/rtfpessoa/diff2html/pull/446/files?diff=unified&w=1) and seems like it works.

For me the most important things missing are:
* Typescript types support
* Seems like codegen is not optimal since some functions have unused parameters, for example
* Would be great to have a script to pre-compile templates into a file that you can bundle in your app like hulk.js did and similar to what I did in this PR

Do you think these are things you will be interested in doing?

**Comment by jgonggrijp** [comment]
Yes, the first and the last point are planned. Please clarify the middle point!

**Comment by jgonggrijp** [comment]
Potentially relevant issue tickets, in case you want to track them:

- [ ] [#12 TypeScript and Flow typings](https://gitlab.com/jgonggrijp/wontache/-/issues/12)
- [ ] [#13 Command line interface](https://gitlab.com/jgonggrijp/wontache/-/issues/13)
- [x] [#25 Template module wrapper](https://gitlab.com/jgonggrijp/wontache/-/issues/25) (implemented but not yet released)
- [ ] [#16 WebPack plugin](https://gitlab.com/jgonggrijp/wontache/-/issues/16)

**Comment by rtfpessoa** [comment]
Do you have any ideas for timelines here?

**Comment by jgonggrijp** [comment]
As far as order is concerned, the [development board](https://gitlab.com/jgonggrijp/wontache/-/boards) conveys best how I prioritize the issues. I want to finish the evaluation release milestone this year if I can help it, and the official launch milestone as soon as possible after that.

As far as calendar time is concerned, unfortunately I can spend at most two days a week on my open source libraries and I have to divide my attention between Wontache, Backbone and Underscore (I took over maintainance of the latter two from the original author). I get to it whenever I get to it, so I cannot promise any particular date.

If you are seriously considering to use Wontache, please let me know which issues are the most important to you. The priorities are somewhat flexible; in fact, I already moved the WebPack plugin up because it seemed relevant to diff2html and I expect it to be quick to implement.

(Also, please consider donating to my [Patreon](https://www.patreon.com/juliangonggrijp) and recruiting other people to do so. Given substantial sponsorship, I might be able to increase my time investment in open source libraries such as Wontache.)

By the way, you mentioned this earlier:

> * Seems like codegen is not optimal since some functions have unused parameters, for example

Please clarify.

**Comment by t1m0thyj** [comment]
@rtfpessoa Would it be possible to publish the `3.0.0-beta.1` tag in the "use-wontache" branch to NPM, since all tests are passing? My team would like to use diff2html but we are not allowed to use deprecated/unmaintained packages. Thanks! 🙏

**Comment by rtfpessoa** [comment]
@t1m0thyj I just released version `3.4.20-usewontache.1.60e7a2e` with the initial wontache implementation.

**Comment by t1m0thyj** [comment]
Thanks for the quick response! So far the beta version seems to be working well for us.

In case anyone else wants to try it out in a TypeScript project, here's what I did to work around `wontache` not having type definitions yet. I created a file `__types__/wontache.d.ts`:
```typescript
// Remove this file once wontache adds type definitions
declare module 'wontache' {
    type CompiledTemplate = any;
    type Partials = any;
}
```
and added this to `tsconfig.json`:
```json
  "files": [
    "./__types__/wontache.d.ts"
  ]
```

**Comment by rtfpessoa** [comment]
I created these more details typings https://github.com/rtfpessoa/diff2html/blob/use-wontache/typings/wontache/wontache.d.ts
